table Veh_IMG
	lineageTag: 671b8782-1388-4941-b5ce-237073a2025d

	column 'Vehicle Type'
		dataType: string
		lineageTag: 531f8fa9-8e98-442c-ab86-f47b0f336a40
		summarizeBy: none
		sourceColumn: Vehicle Type

		annotation SummarizationSetBy = Automatic

	column Img
		dataType: string
		lineageTag: 0b3fe7e7-6379-4872-be6b-106a6a0d0341
		summarizeBy: none
		sourceColumn: Img

		annotation SummarizationSetBy = Automatic

	partition Veh_IMG = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ARYAN SINGH\Desktop\Uber Dashboard Dashboard\Dataset-20260605T163043Z-3-001\Dataset\uber.xlsx"), null, true),
				    Veh_IMG_Sheet = Source{[Item="Veh_IMG",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Veh_IMG_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Vehicle Type", type text}, {"Img", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

